from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd + '/']

group = DefineGroup('xgui', src, depend = [''], CPPPATH = CPPPATH)

#Return('group')

objs = []
list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')

