import rtconfig
from building import *

cwd = GetCurrentDir()

src     = Glob('src/*/*.c')

path = [cwd + '/']

CPPDEFINES = ['LV_CONF_INCLUDE_SIMPLE', 'LV_EX_CONF_INCLUDE_SIMPLE']


group = DefineGroup('lvgl', src, depend = ['RT_USING_LVGL'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
